version: '3.4'


services:

    #######################################################
    #  Ngnix
    #######################################################
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:443"
      - "3000:444"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - rabbitmq
      - authentication
      - notification
      - redis
    networks:
      - backend_network


    #######################################################
    #  Redis
    #######################################################
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    networks:
      - backend_network

  redis-client:
    image: redis:latest
    container_name: redis-client
    command: redis-cli -h redis
    networks:
      - backend_network


    #######################################################
    #  Rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672"
      - "15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend_network

    #######################################################
    #  Authentication
    #######################################################
  authentication:
    image: authentication
    container_name: authentication
    restart: unless-stopped
    ports:
      - "3000"
    networks:
      - backend_network
    depends_on:
      - rabbitmq
      - redis


    #######################################################
    #  Notification
    #######################################################
  notification:
    image: notification
    container_name: notification
    restart: unless-stopped
    ports:
      - "3005"
    networks:
      - backend_network
    depends_on:
      - rabbitmq

  client:
    image: client
    container_name: client
    restart: unless-stopped
    ports:
      - "3008"
    networks:
      - backend_network
        
networks:
  backend_network:
    driver: bridge

volumes:
  rabbitmq_data:
  
